name: Node Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  test_pull_request:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node_version: 16.16.0
      - run: npm ci
      - run: npm run test:unit
      - run: npm run build
